server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  profiles:
    active: after-route
---
spring:
  profiles: after_route
  cloud:
    gateway:
      routes:
        - id: after-route
          uri: http://localhost:8763/api/hi
          predicates:
            - After=2019-12-29T10:49:47.789-07:00[America/Denver]
