server:
  port: 8763

spring:
  application:
    name: feign-client
#  关闭重试机制开关
  cloud:
    loadbalancer:
      retry:
        enabled: true
sevice-feign:
  ribbon:
    MaxAutoRetries: 3
    MaxAutoRetriesNextServer: 3
    ReadTimeout: 2000
    OkToRetryOnAllOperations: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#  Feign是自带断路器的，在D版本的Spring Cloud之后，它没有默认打开。需要在配置文件中配置打开它，在配置文件加以下代码：
feign:
  hystrix:
    enabled: true
hystrix:
  commad:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 9000